### ISSUE TITLE
修改KubeSphere 控制台绑定的 EIP ID参数后，没有生效

### ISSUE THREAD

**Issue by mayuhope** [QingCloudAppcenter/QKE#106]
1、QKE集群安装了ks；

2、在配置参数中将KubeSphere 控制台绑定的 EIP ID进行修改，绑定到其他IP，但是发现KubeSphere 控制台 URL这里的IP地址还是之前的，没有改变；

3、查看pod状态，是正常的
![image](https://user-images.githubusercontent.com/7677050/62597105-7cc23700-b917-11e9-9060-29e26f41bef9.png)

**Comment by wnxn** [comment]
复现了， @magicsong 看看

**Comment by magicsong** [comment]
@wnxn @mayuhope 由于平台的问题，更新一个LB的eip需要至少三分钟，要等待一会
