### ISSUE TITLE
更新 KS only installer 容器镜像，更新ks-docs镜像，ks-console增加pod反亲和性调度

### ISSUE THREAD

**Issue by pixiake** [QingCloudAppcenter/QKE#107]
kubesphere/docs.kubesphere.io:advanced-2.0.0  替换为  kubesphere/ks-docs:advanced-2.0.2

kubespheredev/ks-installer:advanced-2.0.2   替换为  kubesphere/ks-installer:advanced-2.0.2

**Comment by wnxn** [comment]
更新：
https://github.com/QingCloudAppcenter/QKE/blob/4c75bc357af4cf6180684e7b321bfb6aa5b0b84b/confd/templates/k8s/kubesphere-installer.yaml.tmpl#L145
