### ISSUE TITLE
支持新类型主机

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#144]
**What would you like to be added**:
支持企业型 node_e1(考虑与企业型 e2 主机区分)，基础型主机 node_std
新建 QKE 集群不再支持 性能型 node_super_perf，超高性能型主机 node_perf
升级使用 in place 升级，不改变主机类型

**Why is this needed**:

**Comment by wnxn** [comment]
in place 升级不会改变升级前的主机类型

**Comment by wnxn** [comment]
Console 预制资源配置：开发测试环境，高性能开发测试环境，生产环境，高性能生产环境

**Comment by hlwanghl** [comment]
Done by #182
