### ISSUE TITLE
初始化集群时没完成 KS 安装应返回非 0

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#147]
**What happened**:
选择 0 个 node， QKE 集群创建成功后没报错

**What you expected to happen**:
选择 0 个 node，QKE 集群完成创建后应报错

**How to reproduce it (as minimally and precisely as possible)**:
选择 0 个 node，创建带 KS 的 QKE 集群。

**Anything else we need to know?**:
启用安装 KS

**Environment**:
- QKE version: v1.0.1
- Cloud resource ID (e.g. region, zone, clusterid, instance id, volume id):
- Others:

**Comment by hlwanghl** [comment]
新版本加了对 ks-installer 日志的判断，日志里报错就会返回非 0。
