### ISSUE TITLE
registry mirror 易配错，增加文案提示

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#150]
**What would you like to be added**:
目前：镜像服务地址，多个用 1 个空格隔开
修改后：镜像 mirror 地址，多个用 1 个空格隔开。非必填项，不是镜像仓库地址。

**Why is this needed**:
很多用户填错此项，造成集群创建失败

**Comment by hlwanghl** [comment]
Fixed by #182 

用正则表达式强制以 http 开头。
