### ISSUE TITLE
支持 GPU 主机类型

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#156]
**What would you like to be added**:
QKE：
QKE 增加新的 role, 称为 node_gpu, instance type 为 201
对于挂盘的能力与 201 类型主机一致

App 框架支持 GPU：https://docs.qingcloud.com/appcenter/docs/specifications/specifications.html#gpu_class

**Why is this needed**:

**Comment by hlwanghl** [comment]
Done by #182
