### ISSUE TITLE
Ubuntu 18 私有云环境下 hosts 解析问题

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#173]
**What happened**:
私有云环境下解析 api.ks.qingcloud.com 失败

**What you expected to happen**:
能够成功解析

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
qke 1.0.0 使用 ubuntu16 无此问题
qke 1.0.1 使用 ubuntu18 有此问题
疑与 ubuntu 18 使用 systemd-resolve 有关。18开始systemd-resolve会让dns指向127.0.0.53环回，它再接管。

> systemd-resolve --statistics 看 dns 状态

**Environment**:
- QKE version:  v1.0.1
- Cloud resource ID (e.g. region, zone, clusterid, instance id, volume id):
- Others:

**Comment by hlwanghl** [comment]
Fixed by:

https://github.com/QingCloudAppcenter/QKE/blob/042800021519acbb28e669dadd59b631c430dca8/app/cluster.json.mustache#L10
