### ISSUE TITLE
新建 Kubernetes v1.16 集群

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#177]
**What would you like to be added**:
1. 确定各组件版本，如 dns, calico, flannel, etcd
2. 确定 LB，CSI 插件版本

**Why is this needed**:

**Comment by wnxn** [comment]
In KS 2.1.1
k8s v1.16.7
etcd v3.2.18
calico v3.7.3
coredns 1.6.0

**Comment by hlwanghl** [comment]
- [ ] etcd binary install - systemd
- [ ] install k8s 1/3-node cluster by kubeadm
- [ ] net plugin: calico, flannel
- [ ] storage plugin: csi qingcloud
- [ ] offline docker images
- [ ] docker auto prune
- [ ] log rotate
- [ ] LB for HA cluster
- [ ] external etcd
- [ ] external ELK

**Comment by hlwanghl** [comment]
Done by #182
