### ISSUE TITLE
improve kubeconfig tab

### ISSUE THREAD

**Issue by hlwanghl** [QingCloudAppcenter/QKE#194]
目前版本用户下载 kubeconfig 后，如果配置了公网IP，还需要自己把 `server` 的值相应修改一下。后续版本可以直接在生成 kubeconfig 的时候，检测一下集群参数，把 `/env/kubernetes_eip` 的值直接填进去，方便用户使用。

**Comment by MrYourM** [comment]
👌

**Comment by hlwanghl** [comment]
Done.
