### ISSUE TITLE
disable ssh by default

### ISSUE THREAD

**Issue by hlwanghl** [QingCloudAppcenter/QKE#241]
start ssh at start cmd for security.

**Comment by MrYourM** [comment]
这个会影响到 k8s 本身的创建和文件的传递吧

**Comment by hlwanghl** [comment]
放到 SERVICES 里了。start 的时候启动。这样就跟其他 app 统一起来了。

**Comment by MrYourM** [comment]
在什么情况下 disabled ssh 呢？看起来起来找不到明确关闭 ssh 的情况

**Comment by hlwanghl** [comment]
用 make.sh 做映像的时候会统一关闭 ssh，就不需要单独为了 QKE 临时改代码了。
