### ISSUE TITLE
[single-master] CNI plugin configurable

### ISSUE THREAD

**Issue by magicsong** [QingCloudAppcenter/QKE#25]
- [x] 用户可以在Flannel和Calico中选择，默认是calico

**Comment by wnxn** [comment]
https://github.com/QingCloudAppcenter/QKE/blob/8c08b53eddf6fb8cc6f51e441e0cc7f0e22f388c/app/config/config.json#L391-L398

**Comment by wnxn** [comment]
https://github.com/QingCloudAppcenter/QKE/blob/8c08b53eddf6fb8cc6f51e441e0cc7f0e22f388c/app/config/config.json#L410-L419
