### ISSUE TITLE
开发版测试发现的问题

### ISSUE THREAD

**Issue by calvinyv** [QingCloudAppcenter/QKE#34]
* [x] 集群默认计算节点是3个？最好真个最少数. 已改为 2 个 node
 * [x] app默认 名称和描述都要改，比如名称是 QKE，描述是QingCloud Kubernetes Engine。已改
 * [x] neonsan支持么？支持，待在有 NeonSAN 区测试
 * [x] 基础、企业主机和硬盘支持么？不支持，有的区不支持会报错
 * [x] 参考其他app给个正式版本名称吧，不要用demo1。 已改为 KubeSphere 2.0.0 - QingCloud 1.0.0
 * [x] eip环境变量上提，放到第二个的位置. 已修改

**Comment by wnxn** [comment]
1.集群默认计算节点是3个？最好整个最少数。挂盘要 14 个盘，

**Comment by calvinyv** [comment]
1个master2node应该够了吧

**Comment by wnxn** [comment]
* [x] 集群默认计算节点是3个？最好真个最少数. 已改为 2 个 node
 * [x] app默认 名称和描述都要改，比如名称是 QKE，描述是QingCloud Kubernetes Engine。已改
 * [x] neonsan支持么？支持，待在有 NeonSAN 区测试
 * [x] 基础、企业主机和硬盘支持么？不支持，有的区不支持会报错
 * [x] 参考其他app给个正式版本名称吧，不要用demo1。 已改为 KubeSphere 2.0.0 - QingCloud 1.0.0
 * [x] eip环境变量上提，放到第二个的位置. 已修改
