### ISSUE TITLE
[Ben]更新 Ubuntu 操作系统版本

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#47]
@benjaminhuo 需要更新到哪个 ubuntu 版本呢？对应公有云映像 Id 是多少？

**Comment by benjaminhuo** [comment]
ubuntu 16 有问题，看来只能是 ubuntu18 了，我看只有云上只有 18 的这个版本，这个应该可以 ：bionic1x64c ， Ubuntu Server 18.04.1 LTS 64bit
