### ISSUE TITLE
[Ray] 自动识别集群所在 zone 是否有 neonsan

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#50]
自动识别集群所在zone是否有NeonSAN，如果有就设置其为default sc。IaaS有zone sc的api

**Comment by wnxn** [comment]
目前设计：默认 sc 与 master 主机挂的 data 盘类型一致，默认 sc 的 yaml 定义文件会从 metadata 里渲染，默认 sc 的硬盘类型与资源预检也有关系。
资源预检是在创建 qke 之前检查的。
自动识别集群所在zone是否有NeonSAN 是放在创建 qke 集群的哪个阶段执行呢？ @rayzhou2017 @chilianyi

**Comment by wnxn** [comment]
QKE v1.0.1 ：当 zone 有 neonsan，添加 neonsan 的 sc。

**Comment by chilianyi** [comment]
<img width="1070" alt="屏幕快照 2019-07-09 上午11 31 53" src="https://user-images.githubusercontent.com/5917832/60857456-3062d900-a23d-11e9-927a-c07a70e6c42e.png">

这个api是非公开的，那我们还是注册到metadata中，然后qke 去取吧，这个不会经常变动。 现在qke 只需要用到 neonsan这个信息对吗，还有其他到信息吗， 比如主机类型， gpu类型等等？

**Comment by wnxn** [comment]
@chilianyi   目前开发的 qke 只需要知道 这个 zone 有没有 neonsan。有 neonsan 时就添加一个 neonsan sc。默认 sc 硬盘类型与主机 /data 挂盘类型一致。

**Comment by chilianyi** [comment]
metadata 下 注册了如下信息，可以根据 valid_volume_classes 来判断是否包含neonsan，5为闪存，6为机械硬盘。
```
/self
  /cluster
    /resource_limits
      /valid_volume_classes [comma-separated valid volume classes]
      /valid_instance_classes [comma-separated valid instance classes]
```

**Comment by wnxn** [comment]
> metadata 下 注册了如下信息，可以根据 valid_volume_classes 来判断是否包含neonsan，5为闪存，6为机械硬盘。
> 
> ```
> /self
>   /cluster
>     /resource_limits
>       /valid_volume_classes [comma-separated valid volume classes]
>       /valid_instance_classes [comma-separated valid instance classes]
> ```

@chilianyi 
5为闪存意思是 5 为 NeonSAN么？
6是机械硬盘是指哪种 IaaS 硬盘类型呢？
这个功能什么时候上线呢？

**Comment by wnxn** [comment]
与 @chilianyi  线下讨论，集成 ks ae 2.0.2 的 QKE 处理方法如下：
识别到 5 创建 NeonSAN 存储类型。
因为 ks ae 2.0.2 的  qingcloud csi v0.2.1 引用的 qingcloud sdk go 不支持 type 为 6 的硬盘，所以 6 不做处理。https://github.com/yunify/qingcloud-csi/blob/v0.2.1/vendor/github.com/yunify/qingcloud-sdk-go/service/volume.go#L172
