### ISSUE TITLE
[RunZeXia] 用户直接在本地使用kubectl

### ISSUE THREAD

**Issue by runzexia** [QingCloudAppcenter/QKE#54]
方案1： 使用绑定公网ip的形式
[ ] 高可用时，LB绑定公网IP -> 生成带有LB IP的证书-> 页面提供kubeconfig/crt
[ ] 非高可用时，集群master节点绑定公网IP-> 生成带有EIP的证书-> 页面提供kubeconfig/crt

**Comment by runzexia** [comment]
目前测试了一个正在运行的QKE升级，方案可以通过。

高可用方案下会使用LB作为apiserver访问的入口。
在内网访问时使用vpc内私网 IP进行访问。
在外网访问时为LB绑定公网 IP，提供访问。

升级步骤如下操作

1.所有master节点删除 kubeadm目录下的下列六个文件
```
front-proxy-client.crt
front-proxy-client.key
apiserver.crt
apiserver.key
apiserver-kubelet-client.crt
apiserver-kubelet-client.key
```
2. 修改kubeadm-config.yaml，在certSANs当中加入公网IP，此操作需要注册到confd（观察配置会自动reload）
```
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - loadbalancer
      - 139.198.190.212
```
3.重新生成第一步中删除的crt、key
```
# Create Cert Files
log "start init certs"
kubeadm init phase certs apiserver --config ${KUBEADM_CONFIG_PATH} 
kubeadm init phase certs apiserver-kubelet-client --config ${KUBEADM_CONFIG_PATH}
kubeadm init phase certs front-proxy-client --config ${KUBEADM_CONFIG_PATH}
log "finish init certs"
# Write KubeConfig file to disk
log "start create kubeconfig"
kubeadm init phase kubeconfig all --config ${KUBEADM_CONFIG_PATH}
# Set Kubelet Args
# Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
# Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
# Restart the kubelet service 
log "set kubelet args"
kubeadm init phase kubelet-start --config ${KUBEADM_CONFIG_PATH}
# Write Static Pod manifest
log "write manifest"
kubeadm init phase control-plane all --config ${KUBEADM_CONFIG_PATH}
```
4.重启apiserver完成配置修改

**Comment by runzexia** [comment]
方案2： 使用绑定公网ip的形式
此方案的高可用LB形式与方案1相同。
在非高可用情况下，同样为master节点创建LB，并绑定公网IP。
[ ] 非高可用时，同时创建LB-> LB 后端设置master节点 -> LB绑定公网IP-> 生成带有EIP的证书-> 页面提供kubeconfig/crt

优点 ：可以避免用户的节点直接暴露在公网之上，并且不会为集群节点绑定防火墙
缺点 ：用户需要少许额外费用

**Comment by wnxn** [comment]
custom service 让用户填 EIP 的 IP，QKE 生成新证书。
普通单节点 vpc，普通 HA 用 lb，
基础网络单节点？基础网络 HA 用 lb
调研 kubeconfig 填多个 IP。

**Comment by wnxn** [comment]
Jeff 方法：https://tower.im/teams/637817/documents/7563/
