### ISSUE TITLE
高性能生产环境QKE集群创建完成后，日志组件显示为0

### ISSUE THREAD

**Issue by mayuhope** [QingCloudAppcenter/QKE#80]
![image](https://user-images.githubusercontent.com/7677050/62446461-5eccc900-b795-11e9-844d-e00bb6ced52d.png)
![image](https://user-images.githubusercontent.com/7677050/62446483-6ab88b00-b795-11e9-98fc-c5403f0e6fc3.png)

**Comment by wnxn** [comment]
对于外置 ELK，KS UI Logging 显示 0
