### ISSUE TITLE
添加Kubernetes apiserver eip后，主节点状态不正常

### ISSUE THREAD

**Issue by zryfish** [QingCloudAppcenter/QKE#84]
![截屏2019-08-0518 02 52](https://user-images.githubusercontent.com/3326354/62456602-6303e100-b7ab-11e9-96df-33bcda4f854f.png)

**Comment by huanggze** [comment]
再次复现。发现 kube-apiserver CrashLoopBackoff，而且 “[远程访问 Kubernetes 资源](https://git.internal.yunify.com/qingcloud-product-docs/qingcloud-iaas-docs/blob/docs-ks-app/container/qke/index.md#%E8%BF%9C%E7%A8%8B%E8%AE%BF%E9%97%AE-kubernetes-%E8%B5%84%E6%BA%90)” 功能测试不通过

![image](https://user-images.githubusercontent.com/22350668/62457237-ee31a680-b7ac-11e9-9454-144b93d92510.png)

**Comment by wnxn** [comment]
@zryfish  @huanggze 修复了，请验证一下吧

**Comment by wnxn** [comment]
已修复
