### ISSUE TITLE
解绑告警策略后，页面没有自动刷新

### ISSUE THREAD

**Issue by mayuhope** [QingCloudAppcenter/QKE#85]
1、QKE集群，进入监控告警；

2、给节点（非客户端），绑定一个告警策略，提交成功，页面会自动刷新；

3、再次给相同节点解绑告警策略，提交成功，但是页面没有自动刷新，告警图标一直存在；

期望结果：解绑后页面需要自动刷新；

**Comment by wnxn** [comment]
与本仓库 QKE 内容无关
