### ISSUE TITLE
设置配置参数中主机 hosts 记录的为3个hosts时，提示不合法

### ISSUE THREAD

**Issue by mayuhope** [QingCloudAppcenter/QKE#98]
1、在QKE集群的配置参数中对 主机 hosts 记录 这一字段进行修改，设置hosts为3个，中间使用英文逗号隔开，例如：
192.168.0.11    glusterfs-server1,192.168.0.26    glusterfs-server2,192.168.0.22    glusterfs-server3

2、点击保存，结果提示不合法
![image](https://user-images.githubusercontent.com/7677050/62528797-061e2e80-b870-11e9-9009-0bdc694c628f.png)

期望结果：
合法，允许保存

**Comment by wnxn** [comment]
正则写的不正确，？表示匹配前面的子表达式零次或一次，* 表示匹配前面的子表达式任意次。此处应将 ？ 改为 *

```
^((\d{1,3}\.){3}(\d{1,3})\s+(\w|\.|\-)+,)*((\d{1,3}\.){3}(\d{1,3})\s+(\w|\.|\-)+){1}$
```

https://github.com/QingCloudAppcenter/QKE/blob/5a0d08e05a3767e38719307511596e19d086dcc1/app/config/config.json#L436-L443

**Comment by mayuhope** [comment]
已修复
